version: '3'
services:
  judge-mariadb-backend:
    image: clumsysysy/sqloj-judge-mariadb-backend
    networks:
      - t-network
    links:
      - judge-mariadb-database
    ports:
      - "10110:10100"
    environment:
      SQLOJ_PORT: 10100
      SQLOJ_DB_URL: jdbc:mariadb://judge-mariadb-database:3306/
      SQLOJ_DB_USER: root
      SQLOJ_DB_PASSWORD: sy123456
      SQLOJ_PASSWORD: ys654321
  judge-mariadb-database:
    image: clumsysysy/sqloj-judge-mariadb-database
    networks:
      - t-network
    environment:
      MYSQL_ROOT_PASSWORD: sy123456
      MYSQL_USER: test
      MYSQL_PASSWORD: sy123456
      MYSQL_INITDB_SKIP_TZINFO: 1

networks:
  t-network:
    driver: bridge