version: '3'
services:
  judge-redis-backend:
    image: clumsysysy/sqloj-judge-redis-backend
    networks:
      - t-network
    links:
      - judge-redis-database
    ports:
      - "10001:10100"
    environment:
      SQLOJ_PORT: 10100
      SQLOJ_PASSWORD: ys654321
  judge-redis-database:
    image: clumsysysy/sqloj-judge-redis-database
    restart: always
    networks:
      - t-network
    volumes:
      - /data/redis/data:/data
      - /data/redis/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server --requirepass sy123456
    REDIS_PORT: 10001
      REDIS_JUDGE_DATABASE: 1
      REDIS_PASSWORD: sy123456
      REDIS_HOST: judge-redis-database
    
networks:
  t-network:
    driver: bridge